### PR TITLE
Recode whole EventSystem to be much easier to use for the user.

### PR DESCRIPTION
**Pull request by TheJeterLP**
It is using much more Reflection now, and EventHandlers can be registered with one single method and executed with one signle method.

Include cancelling of events.

Custom Constructors of the Listeners are possible the object is stored.
This way it is even faster because the EventListener class does not have to be created by the system.
Multiple EventHandlers for diff Events in one class

(See examples folder)

### CODE REVIEW

**Comment by BossLetsPlays** [comment]
Using more reflection is generally not a good idea, will make load times slower (I have tested, your's is slightly slower). The whole EventHandler registered with one method is a good idea if it weren't for the fact that there more cases where you would need event triggered methods in classes other than the listener, you could call the method from the listener, but then its slightly pointless, and you may not want public access to the method from the other class, if that makes sense.

Cancelling of events is a good idea, I overlooked it as the way I program it would be a useless feature, but others might do things differently.

Custom constructors were already possible.
"Multiple EventHandlers for diff Events in one class" though my annotation was called SubscribeEvent, this was already possible
EventListener not have to be created by the system? Then in your example what is "EventRegistry.registerEvents(new Listener());" for?

**Comment by TheJeterLP** [comment]
It registers the methods in the object which are a valid EventHandler
Am 09.01.2015 02:21 schrieb "BossLetsPlays" <notifications@github.com>:

**Comment by TheJeterLP** [comment]
Also why is the canceling useless The way I have done it? This way it is slower, that's right. But I don't understand why it shouldn't fit to the lib.

**Comment by TheJeterLP** [comment]
Also why is the canceling useless The way I have done it? This way it is slower, that's right. But I don't understand why it shouldn't fit to the lib.

**Comment by BossLetsPlays** [comment]
i said the cancelation was good....

**Pull request closed without merging**
